### ISSUE TITLE
Schematic naming conventions

### ISSUE THREAD

**Issue by TemptorSent** [sjsoftware/centurion-cpu6#6]
Renames for consistency, designation by grid location of pin1:

ALU0 (UF10) -> UF7 + label "ALU0"
ALU1 (UF11) -> UF9 + label "ALU1"

Seq0 (U?) -> UJ7 + label "Seq0"
Seq1 (U?) -> UK7 + label "Seq1"
Seq2 (UL9) -> UL9 + label "Seq2"

**Comment by sjsoftware** [comment]
Board positions updated
