### ISSUE TITLE
UE7 pins A0, A1 are label PL13, PL14 but are not actually wired.

### ISSUE THREAD

**Issue by charlesUnixPro** [sjsoftware/centurion-cpu6#7]
UE7 pins A0, A1 are label PL13, PL14 but are not actually wired.
![UE7](https://github.com/sjsoftware/centurion-cpu6/assets/1438528/f9b96249-c7f6-4ac5-9c55-2e641e86d341)

**Comment by sjsoftware** [comment]
Fixed labels
